services:
  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/00-init-db.sh:ro
      - ../../backend/migrations:/docker-entrypoint-migrations:ro

volumes:
  db_data:
