ALTER TABLE folders ADD COLUMN IF NOT EXISTS encrypted_key bytea;
ALTER TABLE folders ADD COLUMN IF NOT EXISTS is_public BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE folders ADD COLUMN IF NOT EXISTS share_token TEXT;
ALTER TABLE folders ADD COLUMN IF NOT EXISTS description TEXT;
